version: '3.8'

services:
  yolo-trt:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: yolo-rust-trt
    devices:
      - /dev/video0:/dev/video0
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    ports:
      - "8888:8888"
      - "9999:9999/udp"
    volumes:
      - ../models:/app/models
      - ../config:/app/config
      - ../logs:/app/logs
    privileged: true
    restart: unless-stopped
